// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB8AIcf4sJEShSVHjX_vy7bhXeUO1SDbs',
    appId: '1:620798978194:web:3633763e36ed9b39245e4b',
    messagingSenderId: '620798978194',
    projectId: 'furniture-app-b9e0e',
    authDomain: 'furniture-app-b9e0e.firebaseapp.com',
    storageBucket: 'furniture-app-b9e0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQZiMYuxoKuZ9ElbG2Da9X2ZN2Y5nZDe8',
    appId: '1:620798978194:android:ca853467d18bc540245e4b',
    messagingSenderId: '620798978194',
    projectId: 'furniture-app-b9e0e',
    storageBucket: 'furniture-app-b9e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG5js_q6sKQ9fEi4MrI34RePwpJ7-yKaE',
    appId: '1:620798978194:ios:a528b24a6f32c2b5245e4b',
    messagingSenderId: '620798978194',
    projectId: 'furniture-app-b9e0e',
    storageBucket: 'furniture-app-b9e0e.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG5js_q6sKQ9fEi4MrI34RePwpJ7-yKaE',
    appId: '1:620798978194:ios:a528b24a6f32c2b5245e4b',
    messagingSenderId: '620798978194',
    projectId: 'furniture-app-b9e0e',
    storageBucket: 'furniture-app-b9e0e.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB8AIcf4sJEShSVHjX_vy7bhXeUO1SDbs',
    appId: '1:620798978194:web:52724ee19b4acd53245e4b',
    messagingSenderId: '620798978194',
    projectId: 'furniture-app-b9e0e',
    authDomain: 'furniture-app-b9e0e.firebaseapp.com',
    storageBucket: 'furniture-app-b9e0e.firebasestorage.app',
  );
}
